spring.application.name=auth-service

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres-auth
spring.datasource.username=postgres
spring.datasource.password=1robo1

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto

server.port=8081

auth.jwt.expiration-minutes=10
auth.jwt.issuer=robo

