spring.application.name=user

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres-user
spring.datasource.username=postgres
spring.datasource.password=1robo1

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto

spring.security.user.name=test
spring.security.user.password=test

server.port=8082

spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8081/v1/auth/.well-known/jwks.json
