spring.application.name=chat-service

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://postgres:5432/postgres-chat
spring.datasource.username=postgres
spring.datasource.password=1robo1

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

spring.security.user.name=test
spring.security.user.password=test

server.port=8080

spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://auth-service:8080/v1/auth/.well-known/jwks.json
services.user-service.url=http://user-service:8080

spring.kafka.bootstrap-servers=kafka:9092

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
